### ISSUE TITLE
bug: schemaspy failing workflows

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1392]
```
____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              7.0.0-SNAPSHOT

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Running SchemaSpy 7.0.0-SNAPSHOT with Java(Oracle Corporation) 17-ea PID 1 [Linux, 6.2.0-1011-azure, amd64, /usr/local/lib/schemaspy/schemaspy-7.0.0-SNAPSHOT-app.jar] started by java in /
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:[43](https://github.com/bcgov/quickstart-openshift/actions/runs/6204942043/job/16847579601#step:7:44))
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:[49](https://github.com/bcgov/quickstart-openshift/actions/runs/6204942043/job/16847579601#step:7:50))
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.NoClassDefFoundError: java/time/InstantSource
	at org.schemaspy.Main.run(Main.java:109)
	at org.schemaspy.Main.main(Main.java:77)
	... 8 more
Caused by: java.lang.ClassNotFoundException: java.time.InstantSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:432)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:[51](https://github.com/bcgov/quickstart-openshift/actions/runs/6204942043/job/16847579601#step:7:52)9)
	... 10 more
Error: Process completed with exit code 1.
```

**Comment by mishraomp** [comment]
will try with tag [6.2.4](https://hub.docker.com/layers/schemaspy/schemaspy/6.2.4/images/sha256-08290ff34c0fa4c1b28af555fbedf755159e42d02651a987e6077cb40a06f1ff?context=explore) instead of snapshot cc @DerekRoberts
